// export const FONT_SIZES = ['16px', '20px', '24px', '30px', '36px', '42px', '50px', '60px', '70px', '80px', '100px'];
// export const FONT_SIZES = ['30%', '50%', '70%', '90%', '100%', '130%', '150%', '170%', '200%', '250%', '300%'];
export const FONT_NAMES = ['Arial', 'Courier', 'Garamond', 'Tahoma', 'Times New Roman', 'Verdana', 'Amatic SC', 'Caveat', 'Indie Flower', 'Pacifico', 'Palette Mosaic','Style Script'];
export const FONT_NAMES_LOWER = FONT_NAMES.map(function (font){
    return font.toLowerCase().replace(/\s/g, "-");
});
export const LOREM = [
    'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Suspendisse nisl. Integer vulputate sem a nibh rutrum consequat. Integer tempor. Curabitur sagittis hendrerit ante. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Maecenas libero. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Aliquam erat volutpat. Duis viverra diam non justo. Nunc auctor. Nullam sit amet magna in magna gravida vehicula. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Aenean fermentum risus id tortor. Aliquam id dolor. Et harum quidem rerum facilis est et expedita distinctio.',
    'Nulla est. Ut tempus purus at lorem. Cras elementum. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Nulla quis diam. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Mauris elementum mauris vitae tortor. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Curabitur bibendum justo non orci. Fusce tellus. Aliquam erat volutpat. Nunc auctor. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Etiam egestas wisi a erat.',
    'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Suspendisse sagittis ultrices augue. Pellentesque sapien. Aliquam in lorem sit amet leo accumsan lacinia. In convallis. Aliquam id dolor. Pellentesque sapien. Curabitur vitae diam non enim vestibulum interdum. Nunc auctor. Etiam quis quam. Donec quis nibh at felis congue commodo. Suspendisse sagittis ultrices augue. Mauris tincidunt sem sed arcu. Pellentesque sapien. Integer lacinia. Fusce tellus. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Aliquam in lorem sit amet leo accumsan lacinia.',
    'Fusce suscipit libero eget elit. Phasellus faucibus molestie nisl. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Integer imperdiet lectus quis justo. Praesent in mauris eu tortor porttitor accumsan. Mauris elementum mauris vitae tortor. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Etiam dictum tincidunt diam. Maecenas aliquet accumsan leo. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Vivamus luctus egestas leo. Donec vitae arcu. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
    'Vivamus porttitor turpis ac leo. Integer lacinia. Integer vulputate sem a nibh rutrum consequat. Aenean placerat. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Nunc tincidunt ante vitae massa. Cras elementum. Mauris tincidunt sem sed arcu. Sed ac dolor sit amet purus malesuada congue. Praesent dapibus. Etiam dictum tincidunt diam. Aenean vel massa quis mauris vehicula lacinia. Ut tempus purus at lorem. Aenean id metus id velit ullamcorper pulvinar. Maecenas lorem. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante.'
]